name: build-and-test

on:
  push:
  pull_request:

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.SAGHARI_PACKAGES_PAT }}

    - name: Build the project Docker image
      run: |
        docker build . -f ./Antibiogram-Statistics-Api/Dockerfile --tag ghcr.io/medsystems/antibiogram-statistics-api:latest
        