name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish-antibiogram-statistics-api-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.SAGHARI_PACKAGES_PAT }}

    - name: Build the LicenseManagerService Docker image
      run: |
        docker build . -f ./LicenseManagerService/Dockerfile --tag ghcr.io/medsystems/antibiogram-statistics-api:latest
        