name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish-antibiogram-statistics-api-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.SAGHARI_PACKAGES_PAT }}

    - name: Build the Antibiogram-Statistics-Api Docker image
      run: |
        docker build . -f ./Antibiogram-Statistics-Api/Dockerfile --tag ghcr.io/medsystems/antibiogram-statistics-api:latest
        docker push ghcr.io/medsystems/antibiogram-statistics-api:latest
        docker tag ghcr.io/medsystems/antibiogram-statistics-api:latest ghcr.io/medsystems/antibiogram-statistics-api:${{ github.ref }}
        docker push ghcr.io/medsystems/antibiogram-statistics-api:${{ github.ref }}